/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/kintsugi.glb --transform 
Files: public/kintsugi.glb [9.82MB] > C:\Users\MyBook Hype AMD\Desktop\WebProject\artisan\kintsugi-transformed.glb [507.34KB] (95%)
Author: cmzw (https://sketchfab.com/cmzw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kintsugi-8c83e826eeb54139baaf6f94a9098db0
Title: Kintsugi
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}kintsugi-transformed.glb`,
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
      />
    </group>
  );
}

useGLTF.preload("/kintsugi-transformed.glb");
