/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/kintsugi_cup_of_coffee.glb --transform 
Files: public/kintsugi_cup_of_coffee.glb [4.12MB] > C:\Users\MyBook Hype AMD\Desktop\WebProject\artisan\kintsugi_cup_of_coffee-transformed.glb [483.33KB] (88%)
Author: TadenStar (https://sketchfab.com/tadenstar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kintsugi-cup-of-coffee-34c0f28a77844ec2883e5156f5f1ac29
Title: Kintsugi cup of coffee
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}kintsugi_cup_of_coffee-transformed.glb`,
  );
  return (
    <group {...props} position={[-1, 1.5, 0]} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Kintsugi}
        rotation={[0, 0.031, 0]}
      />
      {/* <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Coffee}
        position={[0, 1.062, 0]}
        rotation={[-Math.PI, -0.8, -Math.PI]}
        scale={1.062}
      /> */}
      {/* <mesh geometry={nodes.Object_8.geometry} material={materials.Ground} position={[-4.28, 0, -4.744]} /> */}
    </group>
  );
}

useGLTF.preload("/kintsugi_cup_of_coffee-transformed.glb");
