/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/kintsugi_heart.glb --transform 
Files: public/kintsugi_heart.glb [101.33KB] > C:\Users\MyBook Hype AMD\Desktop\WebProject\artisan\kintsugi_heart-transformed.glb [17.44KB] (83%)
Author: Zahid Zulfiqar (https://sketchfab.com/zahidjxey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kintsugi-heart-3december-day-2-76d15556d3af4bdeaa8eaefa1264ab50
Title: Kintsugi Heart : 3December Day 2
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/kintsugi_heart-transformed.glb",
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Root" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="Sphere002"
            position={[-0.002, 0, 1.414]}
            scale={[1, 0.563, 1]}
          >
            <mesh
              name="Sphere002_0"
              geometry={nodes.Sphere002_0.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <group
            name="Sphere000"
            position={[-0.002, 0, 1.414]}
            scale={[0.932, 0.524, 0.925]}
          >
            <mesh
              name="Sphere000_0"
              geometry={nodes.Sphere000_0.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group
            name="Sphere004"
            position={[-0.002, 0, 1.414]}
            scale={[1, 0.563, 1]}
          >
            <mesh
              name="Sphere004_0"
              geometry={nodes.Sphere004_0.geometry}
              material={materials["Material.004"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/kintsugi_heart-transformed.glb");
